#!/usr/bin/env bash
# Wolfpack Pedigree Lessons Aggregator
# Reads all .wolfpack/plans/*/pedigree.json files, counts tag occurrences
# across the last N hunts, and writes .wolfpack/pedigree/lessons.md.
#
# Usage: ./scripts/wolfpack-lessons.sh [--last=N]
# Default: last 10 hunts

set -euo pipefail

LAST=${1:-10}
LAST=${LAST#--last=}

REPO_ROOT="$(git rev-parse --show-toplevel)"
PEDIGREE_DIR="$REPO_ROOT/.wolfpack/pedigree"
PLANS_DIR="$REPO_ROOT/.wolfpack/plans"
OUTPUT="$PEDIGREE_DIR/lessons.md"

# Collect all pedigree.json files, sorted by date (newest first)
PEDIGREE_FILES=$(find "$PLANS_DIR" -name "pedigree.json" -exec stat --format='%Y %n' {} \; 2>/dev/null | sort -rn | head -"$LAST" | awk '{print $2}')

if [ -z "$PEDIGREE_FILES" ]; then
    echo "No pedigree.json files found in $PLANS_DIR"
    exit 0
fi

# Count tags
declare -A NEG_TAGS
declare -A POS_TAGS
HUNT_COUNT=0

for f in $PEDIGREE_FILES; do
    HUNT_COUNT=$((HUNT_COUNT + 1))
    # Extract all tags from execution_scores
    TAGS=$(python3 -c "
import json, sys
try:
    d = json.load(open('$f'))
    for dim in d.get('execution_scores', {}).values():
        if isinstance(dim, dict) and 'tags' in dim:
            for t in dim['tags']:
                print(t)
except: pass
" 2>/dev/null)

    for tag in $TAGS; do
        # Classify as negative or positive based on known lists
        case "$tag" in
            missing_plan_item|scope_creep|silent_default|n_plus_one|compliance_oversight|deviation_unjustified|precedent_ignored|symptom_fix|fragile_implementation|wrong_layer|reinvented_wheel|unjustified_simplicity|excessive_deferrals|pointer_overreach|pointer_missed_bug|code_review_false_positive|weak_test_coverage|test_infra_confusion|flaky_test_written|tier_under_classified|tier_over_classified|model_selection_miss|standards_violation|context_wander|transient_test_infra|bloodhound_overreach|incomplete_ui_coverage|forgot_related_name|forgot_changelog_entry|forgot_todo_removal|missing_test_for_change|multi_tenancy_leak)
                NEG_TAGS[$tag]=$(( ${NEG_TAGS[$tag]:-0} + 1 ))
                ;;
            *)
                POS_TAGS[$tag]=$(( ${POS_TAGS[$tag]:-0} + 1 ))
                ;;
        esac
    done
done

# Write lessons.md
cat > "$OUTPUT" << 'HEADER'
# Wolfpack Pedigree Lessons

Auto-generated by `scripts/wolfpack-lessons.sh`. Do not edit manually.
Alpha reads this file during planning to avoid recurring issues and replicate successful patterns.

HEADER

echo "## Recurring Issues (last $HUNT_COUNT hunts)" >> "$OUTPUT"
echo "" >> "$OUTPUT"

if [ ${#NEG_TAGS[@]} -eq 0 ]; then
    echo "(none)" >> "$OUTPUT"
else
    for tag in $(echo "${!NEG_TAGS[@]}" | tr ' ' '\n' | sort); do
        echo "- \`$tag\` — ${NEG_TAGS[$tag]} occurrence(s)" >> "$OUTPUT"
    done
fi

echo "" >> "$OUTPUT"
echo "## Patterns That Work (last $HUNT_COUNT hunts)" >> "$OUTPUT"
echo "" >> "$OUTPUT"

if [ ${#POS_TAGS[@]} -eq 0 ]; then
    echo "(none)" >> "$OUTPUT"
else
    for tag in $(echo "${!POS_TAGS[@]}" | tr ' ' '\n' | sort); do
        echo "- \`$tag\` — ${POS_TAGS[$tag]} occurrence(s)" >> "$OUTPUT"
    done
fi

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "*Generated $(date -Iseconds) from $HUNT_COUNT hunts.*" >> "$OUTPUT"

echo "Wrote $OUTPUT ($HUNT_COUNT hunts, ${#NEG_TAGS[@]} negative tags, ${#POS_TAGS[@]} positive tags)"
