#!/usr/bin/env bash
# scripts/wolfpack-lessons.sh — regenerate .wolfpack/pedigree/lessons.md
# from accumulated pedigree.json files.
#
# Reads every .wolfpack/plans/*/pedigree.json, counts tag occurrences
# across the last N hunts (default 10), and writes the lessons file.
#
# Idempotent — safe to run anytime. Watchdog calls this at end of cert.

set -euo pipefail

PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [[ -z "$PROJECT_ROOT" ]]; then
  echo "Not in a git repo — cannot locate .wolfpack/ directory" >&2
  exit 1
fi
cd "$PROJECT_ROOT"

PEDIGREE_DIR=".wolfpack/pedigree"
PLANS_DIR=".wolfpack/plans"
LESSONS="$PEDIGREE_DIR/lessons.md"
WINDOW="${WOLFPACK_LESSONS_WINDOW:-10}"
MIN_RECURRING="${WOLFPACK_MIN_RECURRING:-2}"
MIN_PATTERN="${WOLFPACK_MIN_PATTERN:-3}"

mkdir -p "$PEDIGREE_DIR"

if [[ ! -d "$PLANS_DIR" ]]; then
  cat > "$LESSONS" <<EOF
# Pedigree Lessons

No $PLANS_DIR/ exists yet. After 1+ Watchdog cert with structured tags,
this file will populate.

_Generated by scripts/wolfpack-lessons.sh_
EOF
  echo "Wrote empty $LESSONS — no plans dir found"
  exit 0
fi

# Collect (mtime, path) for the last $WINDOW pedigree.json files
mapfile -t pedigree_files < <(
  find "$PLANS_DIR" -maxdepth 2 -name pedigree.json -type f -printf '%T@ %p\n' 2>/dev/null \
    | sort -rn \
    | head -n "$WINDOW" \
    | awk '{print $2}'
)

if [[ ${#pedigree_files[@]} -eq 0 ]]; then
  cat > "$LESSONS" <<EOF
# Pedigree Lessons

No completed hunts with pedigree.json yet. After 1+ Watchdog cert with
structured tags, this file will populate.

_Generated by scripts/wolfpack-lessons.sh_
EOF
  echo "Wrote empty $LESSONS — no pedigree.json files found"
  exit 0
fi

# Use jq if available — gives us reliable JSON parsing for tags.
if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found — install jq (apt install jq) to enable lessons aggregation" >&2
  exit 0
fi

# Two passes: positive tags vs negative tags. Vocabulary lists from watchdog skill.
NEGATIVE_TAGS=(
  missing_plan_item incomplete_ui_coverage forgot_related_name
  forgot_changelog_entry forgot_todo_removal silent_default
  n_plus_one missing_test_for_change compliance_oversight
  multi_tenancy_leak scope_creep deviation_unjustified
  bloodhound_overreach context_wander transient_test_infra
  precedent_ignored standards_violation
  symptom_fix fragile_implementation wrong_layer reinvented_wheel
)
POSITIVE_TAGS=(
  canonical_pattern edge_case_coverage clean_first_run
  clear_shepherd_log proactive_changelog proportional_review
  compliance_thorough smoke_steps_clear
  root_cause_fix robust_implementation framework_native
)

is_negative() {
  local tag="$1"
  for t in "${NEGATIVE_TAGS[@]}"; do
    [[ "$t" == "$tag" ]] && return 0
  done
  return 1
}

# Build tag -> count map and tag -> recent-features list
declare -A tag_count
declare -A tag_recent  # space-separated feature slugs

for f in "${pedigree_files[@]}"; do
  feature=$(jq -r '.feature // "unknown"' "$f" 2>/dev/null || echo "unknown")
  # Extract all tags across all dimensions
  while IFS= read -r tag; do
    [[ -z "$tag" || "$tag" == "null" ]] && continue
    tag_count[$tag]=$(( ${tag_count[$tag]:-0} + 1 ))
    tag_recent[$tag]="${tag_recent[$tag]:-} $feature"
  done < <(jq -r '
    .execution_scores
    | to_entries
    | map(select(.value | type == "object"))
    | map(.value.tags // [])
    | flatten
    | .[]
  ' "$f" 2>/dev/null || true)
done

# Write lessons.md
{
  echo "# Pedigree Lessons"
  echo
  echo "Aggregated patterns from the last ${#pedigree_files[@]} hunts (window: $WINDOW)."
  echo "Updated by \`scripts/wolfpack-lessons.sh\`, called at end of every Watchdog cert."
  echo "Last regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "## Patterns That Work (count >= $MIN_PATTERN)"
  echo
  found_pattern=0
  for tag in "${POSITIVE_TAGS[@]}"; do
    count="${tag_count[$tag]:-0}"
    if [[ "$count" -ge "$MIN_PATTERN" ]]; then
      recent=$(echo "${tag_recent[$tag]:-}" | xargs -n1 | sort -u | head -3 | paste -sd, - | sed 's/,/, /g')
      echo "- \`$tag\` (${count}x) — recent: ${recent}"
      found_pattern=1
    fi
  done
  [[ "$found_pattern" -eq 0 ]] && echo "_(none yet)_"
  echo
  echo "## Recurring Issues (count >= $MIN_RECURRING)"
  echo
  found_issue=0
  for tag in "${NEGATIVE_TAGS[@]}"; do
    count="${tag_count[$tag]:-0}"
    if [[ "$count" -ge "$MIN_RECURRING" ]]; then
      recent=$(echo "${tag_recent[$tag]:-}" | xargs -n1 | sort -u | head -3 | paste -sd, - | sed 's/,/, /g')
      echo "- \`$tag\` (${count}x) — recent: ${recent}"
      found_issue=1
    fi
  done
  [[ "$found_issue" -eq 0 ]] && echo "_(none yet)_"
  echo
  # Banned Approaches section
  echo "## Banned Approaches"
  echo
  echo "Approaches that demonstrably failed. Alpha MUST NOT propose these without explicit justification."
  echo
  found_banned=0
  for f in "${pedigree_files[@]}"; do
    feature=$(jq -r '.feature // "unknown"' "$f" 2>/dev/null || echo "unknown")
    while IFS= read -r line; do
      [[ -z "$line" || "$line" == "null" ]] && continue
      desc=$(echo "$line" | jq -r '.description // empty' 2>/dev/null)
      reason=$(echo "$line" | jq -r '.reason // empty' 2>/dev/null)
      if [[ -n "$desc" ]]; then
        echo "- $desc — failed in: $feature. Reason: ${reason:-unspecified}"
        found_banned=1
      fi
    done < <(jq -c '.banned_approaches // [] | .[]' "$f" 2>/dev/null || true)
  done
  [[ "$found_banned" -eq 0 ]] && echo "_(none yet)_"
  echo

  # Parallelism Trends section
  echo "## Parallelism Trends"
  echo
  total_sub_agents=0
  total_redundancy=0
  redundancy_count=0
  high_value_hunts=""
  low_value_hunts=""
  for f in "${pedigree_files[@]}"; do
    feature=$(jq -r '.feature // "unknown"' "$f" 2>/dev/null || echo "unknown")
    spawned=$(jq -r '.parallelism_metrics.sub_agents_spawned // 0' "$f" 2>/dev/null || echo 0)
    total_sub_agents=$((total_sub_agents + spawned))
    redund=$(jq -r '.parallelism_metrics.redundancy_rate // empty' "$f" 2>/dev/null)
    if [[ -n "$redund" && "$redund" != "null" ]]; then
      total_redundancy=$(echo "$total_redundancy + $redund" | bc 2>/dev/null || echo "$total_redundancy")
      redundancy_count=$((redundancy_count + 1))
    fi
    value=$(jq -r '.parallelism_metrics.value_added_by_parallelism // empty' "$f" 2>/dev/null)
    case "$value" in
      high) high_value_hunts="$high_value_hunts $feature" ;;
      low|none) low_value_hunts="$low_value_hunts $feature" ;;
    esac
  done
  hunt_count=${#pedigree_files[@]}
  if [[ "$hunt_count" -gt 0 ]]; then
    avg_agents=$(echo "scale=1; $total_sub_agents / $hunt_count" | bc 2>/dev/null || echo "N/A")
    echo "- Average sub-agents per hunt: $avg_agents"
  fi
  if [[ "$redundancy_count" -gt 0 ]]; then
    avg_redundancy=$(echo "scale=1; $total_redundancy * 100 / $redundancy_count" | bc 2>/dev/null || echo "N/A")
    echo "- Average redundancy rate: ${avg_redundancy}%"
  else
    echo "- Average redundancy rate: _(no data yet)_"
  fi
  high_value_hunts=$(echo "$high_value_hunts" | xargs)
  low_value_hunts=$(echo "$low_value_hunts" | xargs)
  echo "- Hunts where parallelism was high-value: ${high_value_hunts:-_(none yet)_}"
  echo "- Hunts where parallelism was low-value or none: ${low_value_hunts:-_(none yet)_}"
  echo

  echo "## Recommendations for Next Plan"
  echo
  echo "Alpha: read this section before scoping any new hunt. Items below have surfaced enough times to be load-bearing."
  echo
  found_rec=0
  for tag in "${NEGATIVE_TAGS[@]}"; do
    count="${tag_count[$tag]:-0}"
    if [[ "$count" -ge "$MIN_PATTERN" ]]; then
      case "$tag" in
        forgot_changelog_entry)
          echo "- ($count×) Always include \`CHANGELOG.md\` in Files to Modify with the exact \`[Unreleased]\` entry text"
          ;;
        forgot_todo_removal)
          echo "- ($count×) Always include \`TODO.md\` in Files to Modify with the exact line to remove"
          ;;
        missing_plan_item)
          echo "- ($count×) Plans must enumerate every UI surface explicitly — no \"the relevant pages\""
          ;;
        forgot_related_name)
          # TODO(de-fracture): related_name is a Django-ORM-specific convention.
          # Parameterize the framework-specific norm via wolfpack-config.md.
          echo "- ($count×) Every new relation/association must follow the project's relationship-naming convention in the plan, not just \"add relation\""
          ;;
        bloodhound_overreach)
          echo "- ($count×) Trivial plans (≤2 files, <50 lines) get 1-3 findings max — see Bloodhound proportionality"
          ;;
        context_wander)
          echo "- ($count×) Plans should explicitly list files to read; agents should refuse files not on the list"
          ;;
        n_plus_one)
          # TODO(de-fracture): select_related/prefetch_related are Django-ORM-specific.
          # Parameterize the project's N+1 mitigation guidance via wolfpack-config.md.
          echo "- ($count×) Plans touching list views or query chains must specify the project's eager-loading / batched-fetch strategy"
          ;;
        symptom_fix)
          echo "- ($count×) Plans should explicitly name root cause, not just the visible symptom — Shepherd must address the cause"
          ;;
        fragile_implementation)
          echo "- ($count×) Plans should specify edge cases and concurrent-access scenarios — Shepherd must handle them"
          ;;
        precedent_ignored)
          echo "- ($count×) Alpha must run Precedent Scout for UI changes — Shepherd must mirror the named precedent"
          ;;
        standards_violation)
          # TODO(de-fracture): UI-invariant specifics (Tom Select, friendly errors)
          # are project conventions — parameterize via wolfpack-config.md.
          echo "- ($count×) Review the project's UI Invariants in wolfpack-config.md — enforce the project's list/error/component conventions"
          ;;
        *)
          echo "- ($count×) Recurring \`$tag\` — review the canonical fix in watchdog skill vocabulary"
          ;;
      esac
      found_rec=1
    fi
  done
  [[ "$found_rec" -eq 0 ]] && echo "_(none yet — keep tagging hunts and patterns will emerge)_"
  echo
  echo "---"
  echo
  echo "_Vocabulary defined in \`.agents/skills/watchdog/SKILL.md\`. To re-tune thresholds:_"
  echo "_\`WOLFPACK_LESSONS_WINDOW=20 WOLFPACK_MIN_RECURRING=3 ./scripts/wolfpack-lessons.sh\`_"
} > "$LESSONS"

echo "Wrote $LESSONS — ${#pedigree_files[@]} hunts aggregated"
